
package com.oneplus.sms.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "wmgw", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://61.145.229.29:9003/MWGate/wmgw.asmx?wsdl")
public class Wmgw
    extends Service
{

    private final static URL WMGW_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://61.145.229.29:9003/MWGate/wmgw.asmx?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WMGW_WSDL_LOCATION = url;
    }

    public Wmgw(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wmgw() {
        super(WMGW_WSDL_LOCATION, new QName("http://tempuri.org/", "wmgw"));
    }
    /**
     * Add by fengzhihao
     * @param wsdlLocation
     */
    public Wmgw(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://tempuri.org/", "wmgw"));
    }
    /**
     * 
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap")
    public WmgwSoap getWmgwSoap() {
        return (WmgwSoap)super.getPort(new QName("http://tempuri.org/", "wmgwSoap"), WmgwSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap")
    public WmgwSoap getWmgwSoap(WebServiceFeature... features) {
        return (WmgwSoap)super.getPort(new QName("http://tempuri.org/", "wmgwSoap"), WmgwSoap.class, features);
    }

}
